In [11]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Load the CSV file into a dataframe
df = pd.read_csv('C:/Users/Noor/Desktop/owid-covid-data.csv')

In [12]:
# Check number of rows and columns in the dataframe
print("Number of rows and columns:", df.shape)

Number of rows and columns: (309797, 67)

In [13]:
# View the first 10 rows and last 5 rows of the data
print("First 10 rows:")
print(df.head(10))
print("Last 5 rows:")
print(df.tail(5))

First 10 rows:
  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-01-03          NaN        0.0
1      AFG      Asia  Afghanistan  2020-01-04          NaN        0.0
2      AFG      Asia  Afghanistan  2020-01-05          NaN        0.0
3      AFG      Asia  Afghanistan  2020-01-06          NaN        0.0
4      AFG      Asia  Afghanistan  2020-01-07          NaN        0.0
5      AFG      Asia  Afghanistan  2020-01-08          NaN        0.0
6      AFG      Asia  Afghanistan  2020-01-09          NaN        0.0
7      AFG      Asia  Afghanistan  2020-01-10          NaN        0.0
8      AFG      Asia  Afghanistan  2020-01-11          NaN        0.0
9      AFG      Asia  Afghanistan  2020-01-12          NaN        0.0

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         0.0                  NaN  ...
1                 NaN           NaN         0.0                  NaN  ...
2                 NaN           NaN         0.0                  NaN  ...
3                 NaN           NaN         0.0                  NaN  ...
4                 NaN           NaN         0.0                  NaN  ...
5                 0.0           NaN         0.0                  0.0  ...
6                 0.0           NaN         0.0                  0.0  ...
7                 0.0           NaN         0.0                  0.0  ...
8                 0.0           NaN         0.0                  0.0  ...
9                 0.0           NaN         0.0                  0.0  ...

   male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
0           NaN                  37.746                         0.5
1           NaN                  37.746                         0.5
2           NaN                  37.746                         0.5
3           NaN                  37.746                         0.5
4           NaN                  37.746                         0.5
5           NaN                  37.746                         0.5
6           NaN                  37.746                         0.5
7           NaN                  37.746                         0.5
8           NaN                  37.746                         0.5
9           NaN                  37.746                         0.5

   life_expectancy  human_development_index  population  \
0            64.83                    0.511  41128772.0
1            64.83                    0.511  41128772.0
2            64.83                    0.511  41128772.0
3            64.83                    0.511  41128772.0
4            64.83                    0.511  41128772.0
5            64.83                    0.511  41128772.0
6            64.83                    0.511  41128772.0
7            64.83                    0.511  41128772.0
8            64.83                    0.511  41128772.0
9            64.83                    0.511  41128772.0

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN
1                                   NaN                          NaN
2                                   NaN                          NaN
3                                   NaN                          NaN
4                                   NaN                          NaN
5                                   NaN                          NaN
6                                   NaN                          NaN
7                                   NaN                          NaN
8                                   NaN                          NaN
9                                   NaN                          NaN

   excess_mortality  excess_mortality_cumulative_per_million
0               NaN                                      NaN
1               NaN                                      NaN
2               NaN                                      NaN
3               NaN                                      NaN
4               NaN                                      NaN
5               NaN                                      NaN
6               NaN                                      NaN
7               NaN                                      NaN
8               NaN                                      NaN
9               NaN                                      NaN

[10 rows x 67 columns]
Last 5 rows:
       iso_code continent  location        date  total_cases  new_cases  \
309792      ZWE    Africa  Zimbabwe  2023-05-06     264685.0        0.0
309793      ZWE    Africa  Zimbabwe  2023-05-07     264685.0        0.0
309794      ZWE    Africa  Zimbabwe  2023-05-08     264776.0       91.0
309795      ZWE    Africa  Zimbabwe  2023-05-09     264776.0        0.0
309796      ZWE    Africa  Zimbabwe  2023-05-10     264776.0        0.0

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
309792               0.857        5686.0         0.0                0.143
309793               0.286        5686.0         0.0                0.000
309794              13.000        5689.0         3.0                0.429
309795              13.000        5689.0         0.0                0.429
309796              13.000        5689.0         0.0                0.429

        ...  male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
309792  ...          30.7                  36.791                         1.7
309793  ...          30.7                  36.791                         1.7
309794  ...          30.7                  36.791                         1.7
309795  ...          30.7                  36.791                         1.7
309796  ...          30.7                  36.791                         1.7

        life_expectancy  human_development_index  population  \
309792            61.49                    0.571  16320539.0
309793            61.49                    0.571  16320539.0
309794            61.49                    0.571  16320539.0
309795            61.49                    0.571  16320539.0
309796            61.49                    0.571  16320539.0

        excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
309792                                   NaN                          NaN
309793                                   NaN                          NaN
309794                                   NaN                          NaN
309795                                   NaN                          NaN
309796                                   NaN                          NaN

        excess_mortality  excess_mortality_cumulative_per_million
309792               NaN                                      NaN
309793               NaN                                      NaN
309794               NaN                                      NaN
309795               NaN                                      NaN
309796               NaN                                      NaN

[5 rows x 67 columns]

In [14]:
# Show the basic summary of data
print("Summary of data:")
print(df.describe())

Summary of data:
        total_cases     new_cases  new_cases_smoothed  total_deaths  \
count  2.736270e+05  3.009060e+05        2.996420e+05  2.529760e+05
mean   5.720062e+06  1.078888e+04        1.083173e+04  8.034578e+04
std    3.574208e+07  1.033029e+05        1.005335e+05  4.152550e+05
min    1.000000e+00  0.000000e+00        0.000000e+00  1.000000e+00
25%    6.514500e+03  0.000000e+00        1.143000e+00  1.210000e+02
50%    6.209400e+04  1.700000e+01        3.828600e+01  1.225000e+03
75%    6.351960e+05  5.290000e+02        6.352502e+02  1.057925e+04
max    7.659025e+08  7.460827e+06        6.410668e+06  6.927365e+06

          new_deaths  new_deaths_smoothed  total_cases_per_million  \
count  301000.000000        299770.000000            273627.000000
mean       96.218953            96.588991             87308.498902
std       602.347508           593.003157            137715.424666
min         0.000000             0.000000                 0.000000
25%         0.000000             0.000000              2015.598000
50%         0.000000             0.286000             20502.747000
75%         6.000000             6.714000            106547.621000
max     20028.000000         14680.286000            737554.506000

       new_cases_per_million  new_cases_smoothed_per_million  \
count          300906.000000                   299642.000000
mean              162.598372                      163.230068
std              1128.892484                      635.983268
min                 0.000000                        0.000000
25%                 0.000000                        0.254000
50%                 2.474000                       10.811000
75%                69.379500                      104.379250
max            228872.025000                    37241.781000

       total_deaths_per_million  ...   male_smokers  handwashing_facilities  \
count             252976.000000  ...  177637.000000           117538.000000
mean                 808.012643  ...      32.912137               50.794674
std                 1051.355043  ...      13.572587               31.956680
min                    0.000000  ...       7.700000                1.188000
25%                   49.555000  ...      22.600000               20.859000
50%                  336.611500  ...      33.100000               49.839000
75%                 1243.195250  ...      41.300000               83.241000
max                 6466.921000  ...      78.100000              100.000000

       hospital_beds_per_thousand  life_expectancy  human_development_index  \
count               211913.000000    284881.000000            232697.000000
mean                     3.098122        73.720709                 0.722562
std                      2.548769         7.396758                 0.148996
min                      0.100000        53.280000                 0.394000
25%                      1.300000        69.590000                 0.602000
50%                      2.500000        75.050000                 0.740000
75%                      4.200000        79.460000                 0.829000
max                     13.800000        86.750000                 0.957000

         population  excess_mortality_cumulative_absolute  \
count  3.097970e+05                          1.066900e+04
mean   1.284332e+08                          4.739668e+04
std    6.607468e+08                          1.384241e+05
min    4.700000e+01                         -3.772610e+04
25%    4.490020e+05                          2.780000e+01
50%    5.882259e+06                          4.530999e+03
75%    2.830170e+07                          3.159700e+04
max    7.975105e+09                          1.282260e+06

       excess_mortality_cumulative  excess_mortality  \
count                 10669.000000      10669.000000
mean                      9.538903         12.633550
std                      12.914011         26.344219
min                     -44.230000        -95.920000
25%                       0.560000         -1.200000
50%                       7.750000          6.490000
75%                      15.360000         18.070000
max                      76.550000        377.300000

       excess_mortality_cumulative_per_million
count                             10669.000000
mean                               1477.149682
std                                1840.907839
min                               -1984.281600
25%                                  24.645111
50%                                 900.418500
75%                                2399.257000
max                               10291.122000

[8 rows x 62 columns]

In [15]:
# Drop the following columns: new_deaths_smoothed', 'new_cases_per_million', 'total_cases_per_million'
df = df.drop(['new_deaths_smoothed', 'new_cases_per_million', 'total_cases_per_million'], axis=1)

# Rename the following columns: 'date': 'Date', 'location': 'Country', 'continent': 'Continent', 'iso_code': 'ISO_code'
df = df.rename(columns={'date': 'Date', 'location': 'Country', 'continent': 'Continent', 'iso_code': 'ISO_code'})

# List the continent names
continents = df['Continent'].unique()
print("Continent names:")
print(continents)

Continent names:
['Asia' nan 'Europe' 'Africa' 'Oceania' 'North America' 'South America']

In [16]:
# Impute missing values with 0
imputer = SimpleImputer(strategy='constant', fill_value=0)
df = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

# Groupby 'Date' and 'Country' and calculate the sum of 'total_cases', 'total_deaths', 'total_vaccinations'
df3 = df.groupby(['Date', 'Country']).agg({
    'total_cases': 'sum',
    'total_deaths': 'sum',
    'total_vaccinations': 'sum'
}).reset_index()

# Find total countries where total_deaths is greater than 1000000
total_countries = df3[df3['total_deaths'] > 1000000]['Country'].nunique()
print("Total countries where total deaths is greater than 1000000:", total_countries)

# Find how many dates we have in total where total_deaths is greater than 1000000
total_dates = df3[df3['total_deaths'] > 1000000]['Date'].nunique()
print("Total dates where total deaths is greater than 1000000:", total_dates)

Total countries where total deaths is greater than 1000000: 10
Total dates where total deaths is greater than 1000000: 974